Vagrant.configure("2") do |config|
  config.vm.define "centos-7" do |machine|
    machine.vm.box = "centos/7"
    machine.vm.hostname = "centos-7"
  end

  config.vm.define "debian-jessie" do |machine|
    machine.vm.box = "debian/jessie64"
    machine.vm.hostname = "debian-jessie"
  end

  config.vm.define "debian-stretch" do |machine|
    machine.vm.box = "debian/stretch64"
    machine.vm.hostname = "debian-stretch"
  end

  config.vm.define "ubuntu-xenial" do |machine|
    machine.vm.box = "ubuntu/xenial64"
    machine.vm.hostname = "ubuntu-xenial"

    config.vm.provision "shell" do |s|
      s.inline = "apt-get update && apt-get install -y python"
    end
  end

  config.vm.define "ubuntu-bionic" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "ubuntu-bionic"

    config.vm.provision "shell" do |s|
      s.inline = "apt-get update && apt-get install -y python"
    end

    machine.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "test.yml"
    end
  end
end
